export type Category = string;
export type ObraCategory = "pintura" | "artesania";

export interface GalleryImage {
  id: string;
  src: string;
  alt: string;
  title: string;
  description: string;
  category: Category;
  width: number;
  height: number;
}

export interface ObraImage {
  id: string;
  src: string;
  alt: string;
  title: string;
  description: string;
  category: ObraCategory;
  technique?: string;
  year?: string;
  dimensions?: string;
}

const obras: ObraImage[] = [
  {
    id: "p01",
    src: "/obras/temple.jpg",
    alt: "Temple",
    title: "Temple",
    description: "Técnica mixta sobre lienzo",
    category: "pintura",
    technique: "Técnica mixta sobre lienzo",
    dimensions: "60 × 80 cm",
  },
  {
    id: "p02",
    src: "/obras/desnudo-rojo-chagall.jpg",
    alt: "Reproducción de Desnudo rojo sentado de Chagall",
    title: "Desnudo rojo sentado",
    description: "Reproducción de Chagall. Témpera con huevo sobre lienzo.",
    category: "pintura",
    technique: "Témpera con huevo sobre lienzo",
    dimensions: "60 × 80 cm",
  },
  {
    id: "p03",
    src: "/obras/bodegon.jpg",
    alt: "Bodegón",
    title: "Bodegón",
    description: "Óleo sobre lienzo",
    category: "pintura",
    technique: "Óleo sobre lienzo",
    dimensions: "60 × 80 cm",
  },
  {
    id: "p04",
    src: "/obras/murmullos-visuales.jpg",
    alt: "Murmullos visuales",
    title: "Murmullos visuales",
    description: "Acrílico sobre lienzo",
    category: "pintura",
    technique: "Acrílico sobre lienzo",
    dimensions: "50 × 100 cm",
  },
  {
    id: "p05",
    src: "/obras/estel.jpg",
    alt: "Estel",
    title: "Estel",
    description: "Acrílico sobre lienzo",
    category: "pintura",
    technique: "Acrílico sobre lienzo",
    dimensions: "35 × 50 cm",
  },
  {
    id: "p06",
    src: "/obras/valparaiso.jpg",
    alt: "Valparaíso",
    title: "Valparaíso",
    description: "Acrílico sobre lienzo",
    category: "pintura",
    technique: "Acrílico sobre lienzo",
    dimensions: "60 × 80 cm",
  },
  {
    id: "p07",
    src: "/obras/memoria-translucida.jpg",
    alt: "Memoria translúcida",
    title: "Memoria translúcida",
    description: "Acrílico sobre madera",
    category: "pintura",
    technique: "Acrílico sobre madera",
    dimensions: "60 × 80 cm",
  },
  {
    id: "p08",
    src: "/obras/lagrimas-del-sol.jpg",
    alt: "Lágrimas del sol",
    title: "Lágrimas del sol",
    description: "Acuarela",
    category: "pintura",
    technique: "Acuarela",
    dimensions: "40 × 40 cm",
  },
  {
    id: "p09",
    src: "/obras/alma-noble.jpg",
    alt: "Alma noble",
    title: "Alma noble",
    description: "Acrílico sobre lienzo",
    category: "pintura",
    technique: "Acrílico sobre lienzo",
    dimensions: "20 × 30 cm",
  },
  {
    id: "p10",
    src: "/obras/la-hora-del-balcon.jpg",
    alt: "La hora del balcón",
    title: "La hora del balcón",
    description: "Óleo sobre lienzo",
    category: "pintura",
    technique: "Óleo sobre lienzo",
    dimensions: "35 × 50 cm",
  },
  {
    id: "p11",
    src: "/obras/bubucella.jpg",
    alt: "Bubucella",
    title: "Bubucella",
    description: "Acrílico sobre lienzo",
    category: "pintura",
    technique: "Acrílico sobre lienzo",
    dimensions: "22 × 35 cm",
  },
  {
    id: "p12",
    src: "/obras/miradas-al-vuelo.jpg",
    alt: "Miradas al vuelo",
    title: "Miradas al vuelo",
    description: "Acuarela",
    category: "pintura",
    technique: "Acuarela",
    dimensions: "55 × 75 cm",
  },
  {
    id: "p13",
    src: "/obras/resonancias.jpg",
    alt: "Resonancias",
    title: "Resonancias",
    description: "Acuarela",
    category: "pintura",
    technique: "Acuarela",
    dimensions: "35 × 45 cm",
  },
  {
    id: "p14",
    src: "/obras/tango.jpg",
    alt: "Tango",
    title: "Tango",
    description: "Acrílico sobre lienzo",
    category: "pintura",
    technique: "Acrílico sobre lienzo",
    dimensions: "70 × 90 cm",
  },
  {
    id: "p15",
    src: "/obras/valdivia.jpg",
    alt: "Valdivia",
    title: "Valdivia",
    description: "Acrílico sobre lienzo",
    category: "pintura",
    technique: "Acrílico sobre lienzo",
    dimensions: "70 × 90 cm",
  },
  {
    id: "p16",
    src: "/obras/retrato-doble.jpg",
    alt: "Retrato doble",
    title: "Retrato doble",
    description: "Acrílico sobre lienzo",
    category: "pintura",
    technique: "Acrílico sobre lienzo",
    dimensions: "100 × 120 cm",
  },
  {
    id: "p17",
    src: "/obras/la-pose.jpg",
    alt: "La pose",
    title: "La pose",
    description: "Óleo sobre lienzo",
    category: "pintura",
    technique: "Óleo sobre lienzo",
    dimensions: "60 × 80 cm",
  },
  {
    id: "p18",
    src: "/obras/gato.jpg",
    alt: "Gato",
    title: "Gato",
    description: "Acrílico sobre lienzo",
    category: "pintura",
    technique: "Acrílico sobre lienzo",
    dimensions: "30 × 40 cm",
  },
  {
    id: "p19",
    src: "/obras/la-compra.jpg",
    alt: "La compra",
    title: "La compra",
    description: "Acuarela",
    category: "pintura",
    technique: "Acuarela",
    dimensions: "38 × 48 cm",
  },
  {
    id: "p20",
    src: "/obras/transparencia.jpg",
    alt: "Transparencia",
    title: "Transparencia",
    description: "Acuarela",
    category: "pintura",
    technique: "Acuarela",
    dimensions: "38 × 50 cm",
  },
  {
    id: "p21",
    src: "/obras/mapuche.jpg",
    alt: "Mapuche",
    title: "Mapuche",
    description: "Acrílico sobre lienzo",
    category: "pintura",
    technique: "Acrílico sobre lienzo",
    dimensions: "100 × 120 cm",
  },
  {
    id: "p22",
    src: "/obras/mis-pies.jpg",
    alt: "Mis pies",
    title: "Mis pies",
    description: "Acrílico sobre lienzo",
    category: "pintura",
    technique: "Acrílico sobre lienzo",
    dimensions: "25 × 35 cm",
  },
  {
    id: "p23",
    src: "/obras/santiago.jpg",
    alt: "Santiago",
    title: "Santiago",
    description: "Acrílico sobre lienzo",
    category: "pintura",
    technique: "Acrílico sobre lienzo",
    dimensions: "100 × 110 cm",
  },
  {
    id: "p24",
    src: "/obras/transito.jpg",
    alt: "Tránsito",
    title: "Tránsito",
    description: "Acuarela",
    category: "pintura",
    technique: "Acuarela",
    dimensions: "25 × 45 cm",
  },
  {
    id: "p25",
    src: "/obras/junior.jpg",
    alt: "Junior",
    title: "Junior",
    description: "Acrílico sobre cartón tela",
    category: "pintura",
    technique: "Acrílico sobre cartón tela",
    dimensions: "Ø 40 cm",
  },
  {
    id: "a01",
    src: "/obras/artesania_1.jpg",
    alt: "Artesanía",
    title: "Artesanía I",
    description: "Pieza artesanal elaborada a mano",
    category: "artesania",
  },
  {
    id: "a02",
    src: "/obras/artesania_2.jpg",
    alt: "Artesanía",
    title: "Artesanía II",
    description: "Pieza artesanal elaborada a mano",
    category: "artesania",
  },
  {
    id: "a03",
    src: "/obras/artesania_3.jpg",
    alt: "Artesanía",
    title: "Artesanía III",
    description: "Pieza artesanal elaborada a mano",
    category: "artesania",
  },
  {
    id: "a04",
    src: "/obras/artesania_4.jpg",
    alt: "Artesanía",
    title: "Artesanía IV",
    description: "Pieza artesanal elaborada a mano",
    category: "artesania",
  },
  {
    id: "a05",
    src: "/obras/artesania_5.jpg",
    alt: "Artesanía",
    title: "Artesanía V",
    description: "Pieza artesanal elaborada a mano",
    category: "artesania",
  },
  {
    id: "a06",
    src: "/obras/artesania_6.jpg",
    alt: "Artesanía",
    title: "Artesanía VI",
    description: "Pieza artesanal elaborada a mano",
    category: "artesania",
  },
  {
    id: "a07",
    src: "/obras/artesania_7.jpg",
    alt: "Artesanía",
    title: "Artesanía VII",
    description: "Pieza artesanal elaborada a mano",
    category: "artesania",
  },
  {
    id: "a08",
    src: "/obras/artesania_8.jpg",
    alt: "Artesanía",
    title: "Artesanía VIII",
    description: "Pieza artesanal elaborada a mano",
    category: "artesania",
  },
  {
    id: "a09",
    src: "/obras/artesania_9.jpg",
    alt: "Artesanía",
    title: "Artesanía IX",
    description: "Pieza artesanal elaborada a mano",
    category: "artesania",
  },
  {
    id: "a10",
    src: "/obras/artesania_10.jpg",
    alt: "Artesanía",
    title: "Artesanía X",
    description: "Pieza artesanal elaborada a mano",
    category: "artesania",
  },
  {
    id: "a11",
    src: "/obras/artesania_11.jpg",
    alt: "Artesanía",
    title: "Artesanía XI",
    description: "Pieza artesanal elaborada a mano",
    category: "artesania",
  },
  {
    id: "a12",
    src: "/obras/artesania_12.jpg",
    alt: "Artesanía",
    title: "Artesanía XII",
    description: "Pieza artesanal elaborada a mano",
    category: "artesania",
  },
  {
    id: "a13",
    src: "/obras/artesania_13.jpg",
    alt: "Artesanía",
    title: "Artesanía XIII",
    description: "Pieza artesanal elaborada a mano",
    category: "artesania",
  },
  {
    id: "a14",
    src: "/obras/artesania_14.jpg",
    alt: "Artesanía",
    title: "Artesanía XIV",
    description: "Pieza artesanal elaborada a mano",
    category: "artesania",
  },
  {
    id: "a15",
    src: "/obras/artesania_15.jpg",
    alt: "Artesanía",
    title: "Artesanía XV",
    description: "Pieza artesanal elaborada a mano",
    category: "artesania",
  },
  {
    id: "a16",
    src: "/obras/artesania_16.jpg",
    alt: "Artesanía",
    title: "Artesanía XVI",
    description: "Pieza artesanal elaborada a mano",
    category: "artesania",
  },
  {
    id: "a17",
    src: "/obras/artesania_17.jpg",
    alt: "Artesanía",
    title: "Artesanía XVII",
    description: "Pieza artesanal elaborada a mano",
    category: "artesania",
  },
  {
    id: "a18",
    src: "/obras/artesania_18.jpg",
    alt: "Artesanía",
    title: "Artesanía XVIII",
    description: "Pieza artesanal elaborada a mano",
    category: "artesania",
  },
  {
    id: "a19",
    src: "/obras/artesania_19.jpg",
    alt: "Artesanía",
    title: "Artesanía XIX",
    description: "Pieza artesanal elaborada a mano",
    category: "artesania",
  },
  {
    id: "a20",
    src: "/obras/artesania_20.jpg",
    alt: "Artesanía",
    title: "Artesanía XX",
    description: "Pieza artesanal elaborada a mano",
    category: "artesania",
  },
];

export function getObrasByCategory(category: ObraCategory): ObraImage[] {
  return obras.filter((o) => o.category === category);
}

export function getAllObras(): ObraImage[] {
  return obras;
}

export function getFeaturedObras(count: number = 6): ObraImage[] {
  return obras.filter((o) => o.category === "pintura").slice(0, count);
}
